sudo: required
language: go
## home folder is /home/travis/gopath/src/github.com/radanalyticsio/oshinko-cli
services:
- docker
before_install:
## add insecure-registry and restart docker
- pwd
- bash --version
- sudo apt-get install --only-upgrade bash
- bash --version
- sudo cat /etc/default/docker
- sudo service docker stop
- sudo sed -i -e 's/sock/sock --insecure-registry 172.30.0.0\/16/' /etc/default/docker
- sudo cat /etc/default/docker
- sudo service docker start
- sudo service docker status
## chmod needs sudo, so all other commands are with sudo
- sudo mkdir -p /home/travis/gopath/src/github.com/radanalyticsio/oshinko-cli/origin
- sudo chmod -R 766 /home/travis/gopath/src/github.com/radanalyticsio/oshinko-cli/origin
## download oc 1.4.1 binary
- sudo wget https://github.com/openshift/origin/releases/download/v1.4.1/openshift-origin-client-tools-v1.4.1-3f9807a-linux-64bit.tar.gz -P origin/
- sudo wget https://github.com/openshift/origin/releases/download/v1.4.1/openshift-origin-server-v1.4.1-3f9807a-linux-64bit.tar.gz -P origin/
- sudo ls -l /home/travis/gopath/src/github.com/radanalyticsio/oshinko-cli/origin
- sudo tar -xvzf /home/travis/gopath/src/github.com/radanalyticsio/oshinko-cli/origin/openshift-origin-client-tools-v1.4.1-3f9807a-linux-64bit.tar.gz
- sudo tar -xvzf /home/travis/gopath/src/github.com/radanalyticsio/oshinko-cli/origin/openshift-origin-server-v1.4.1-3f9807a-linux-64bit.tar.gz
- sudo chmod -R 766 /home/travis/gopath/src/github.com/radanalyticsio/oshinko-cli/
- sudo ls -l /home/travis/gopath/src/github.com/radanalyticsio/oshinko-cli/openshift-origin-client-tools-v1.4.1+3f9807a-linux-64bit
- sudo ls -l /home/travis/gopath/src/github.com/radanalyticsio/oshinko-cli/openshift-origin-server-v1.4.1+3f9807a-linux-64bit
- sudo cp /home/travis/gopath/src/github.com/radanalyticsio/oshinko-cli/openshift-origin-client-tools-v1.4.1+3f9807a-linux-64bit/oc /home/travis/gopath/src/github.com/radanalyticsio/oshinko-cli/origin
- sudo cp /home/travis/gopath/src/github.com/radanalyticsio/oshinko-cli/openshift-origin-server-v1.4.1+3f9807a-linux-64bit/* /home/travis/gopath/src/github.com/radanalyticsio/oshinko-cli/origin
- sudo chmod -R 766 /home/travis/gopath/src/github.com/radanalyticsio/oshinko-cli/origin
- sudo ls -l /home/travis/gopath/src/github.com/radanalyticsio/oshinko-cli/origin
- sudo chmod -R +755 /home/travis/gopath/src/github.com/radanalyticsio/oshinko-cli/origin/*
- sudo cp /home/travis/gopath/src/github.com/radanalyticsio/oshinko-cli/origin/* /bin
- sudo ls -l /bin
- oc version
- export PATH=$PATH:/home/travis/gopath/src/github.com/radanalyticsio/oshinko-cli/origin/
- echo $PATH
## below cmd is important to get oc working in ubuntu
#- sudo docker run -v /:/rootfs -ti --rm --entrypoint=/bin/bash --privileged openshift/origin:v1.4.1 -c "mv /rootfs/bin/findmnt /rootfs/bin/findmnt.backup"
#- sudo /home/travis/gopath/src/github.com/radanalyticsio/oshinko-cli/origin/oc cluster up --host-config-dir=/home/travis/gopath/src/github.com/radanalyticsio/oshinko-cli/origin
#- sudo ls -l /home/travis/gopath/src/github.com/radanalyticsio/oshinko-cli/origin
## find IP:PORT of openshift
#- IPSTR=`sudo /home/travis/gopath/src/github.com/radanalyticsio/oshinko-cli/origin/oc status |grep server`
#- echo $IPSTR
#- IP=${IPSTR##*/}
#- echo ${IP}
install:
before_script:
script:
- make test-cmd
notifications:
 email:
   on_success: never
   on_failure: never

