package clusters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// CreateClusterHandlerFunc turns a function with the right signature into a create cluster handler
type CreateClusterHandlerFunc func(CreateClusterParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateClusterHandlerFunc) Handle(params CreateClusterParams) middleware.Responder {
	return fn(params)
}

// CreateClusterHandler interface for that can handle valid create cluster params
type CreateClusterHandler interface {
	Handle(CreateClusterParams) middleware.Responder
}

// NewCreateCluster creates a new http.Handler for the create cluster operation
func NewCreateCluster(ctx *middleware.Context, handler CreateClusterHandler) *CreateCluster {
	return &CreateCluster{Context: ctx, Handler: handler}
}

/*CreateCluster swagger:route POST /clusters clusters createCluster

Create a new cluster

*/
type CreateCluster struct {
	Context *middleware.Context
	Handler CreateClusterHandler
}

func (o *CreateCluster) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewCreateClusterParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
