package clusters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UpdateSingleClusterHandlerFunc turns a function with the right signature into a update single cluster handler
type UpdateSingleClusterHandlerFunc func(UpdateSingleClusterParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateSingleClusterHandlerFunc) Handle(params UpdateSingleClusterParams) middleware.Responder {
	return fn(params)
}

// UpdateSingleClusterHandler interface for that can handle valid update single cluster params
type UpdateSingleClusterHandler interface {
	Handle(UpdateSingleClusterParams) middleware.Responder
}

// NewUpdateSingleCluster creates a new http.Handler for the update single cluster operation
func NewUpdateSingleCluster(ctx *middleware.Context, handler UpdateSingleClusterHandler) *UpdateSingleCluster {
	return &UpdateSingleCluster{Context: ctx, Handler: handler}
}

/*UpdateSingleCluster swagger:route PUT /clusters/{name} clusters updateSingleCluster

Update the specified cluster

*/
type UpdateSingleCluster struct {
	Context *middleware.Context
	Handler UpdateSingleClusterHandler
}

func (o *UpdateSingleCluster) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewUpdateSingleClusterParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
