#!/usr/bin/env python3
""" validate_swagger

A simple app to validate swagger yaml files.

Usage:

    $ validate_swagger swagger.yaml otherswagger.yaml

If the swagger is valid it will print "Valid" and if not it will dump the
exception trace from the validator.

this application requires the following python packages:
    pyaml
    swagger-spec-validator
"""

import sys

import yaml
from swagger_spec_validator import validator20


if __name__ == '__main__':
    filelist = sys.argv[1:]
    if len(filelist) == 0:
        print('Error: Must supply at least one file to interrogate')
        sys.exit(-1)
    for f in filelist:
        validator20.validate_spec(yaml.load(open(f).read()))
        print('File {} is valid swagger'.format(f))
